### ISSUE TITLE
Add option to disable debug output

### ISSUE THREAD

**Issue by arschles** [deis/object-storage-cli#10]
This issue stems from https://github.com/deis/builder/issues/306

Two options I can think of right now:
- Look for `$DEBUG="1"` in the environment, and only output if it's set
- Add a `--quiet` flag and only output if it's not present

Note that the first option would require no extra work in the [dockerbuilder](https://github.com/deis/dockerbuilder) and [slugbuilder](https://github.com/deis/slugbuilder) codebases (other than downloading an updated CLI binary).

**Comment by bacongobbler** [comment]
option 1 seems like the easy (read: lazy) approach. Therefore, I like that one better. ;)

**Comment by bacongobbler** [comment]
though I'd argue that it listens for DEIS_DEBUG due to issues like https://github.com/deis/workflow/issues/178#issuecomment-214597256
