### ISSUE TITLE
upload builds to s3

### ISSUE THREAD

**Issue by bacongobbler** [deis/object-storage-cli#13]
see https://github.com/deis/workflow-cli/issues/73

Also:
- Limit cross-compilation builds to `darwin/amd64` and `linux/amd64`
- Submit PRs to dependent components:
  - [deis/dockerbuilder](https://github.com/deis/dockerbuilder)
  - [deis/slugbuilder](https://github.com/deis/slugbuilder)
  - [deis/slugrunner](https://github.com/deis/slugrunner)

**Comment by arschles** [comment]
See https://github.com/deis/deisrel/pull/88 for an example implementation
